// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGbKXdWcj-uJWwKbyQd30856NFIQsZxHg',
    appId: '1:129926572164:web:e5078035ec7eb06aa3bad1',
    messagingSenderId: '129926572164',
    projectId: 'ecommerce-18a84',
    authDomain: 'ecommerce-18a84.firebaseapp.com',
    storageBucket: 'ecommerce-18a84.appspot.com',
    measurementId: 'G-BLXM6LB40B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxZXADjSKg6pugMCdn_LGD__RTl3C_h-4',
    appId: '1:129926572164:android:7c1ff2f178c3e71fa3bad1',
    messagingSenderId: '129926572164',
    projectId: 'ecommerce-18a84',
    storageBucket: 'ecommerce-18a84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVZbPjFn8b31mu6z8qgUW06o6KmEDovUI',
    appId: '1:129926572164:ios:5156c37df71ae47fa3bad1',
    messagingSenderId: '129926572164',
    projectId: 'ecommerce-18a84',
    storageBucket: 'ecommerce-18a84.appspot.com',
    androidClientId: '129926572164-clltg50gbksragclds7p72spqrh3pt0f.apps.googleusercontent.com',
    iosClientId: '129926572164-r6gv0a7ni64qtkukvvfdp8uuceo4l7vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );
}
